/*=============================================================================
Project: SeatPM
Team: Joint Effort
School: Seattle Pacific University
Class: CatalyzeU Senior Design

File Name: main.c
Author: Austin Pischer
File Description:
The main() function is where the program always starts executuion.
In addition, all of the global variables in this program should be
declared before the main function.
Also if something is really specific to the SeatPM then it should
probably belong here. For example, "Knee Angle" as opposed to "Angle"
=============================================================================*/

//=============================================================================
// Inclusions
//=============================================================================
/* Inclusions for "coding" */
#include <stdio.h>  // for printf
#include "debug.h"// Debug message toggles
#include "feature_branches.h" // Switching between different opposing features
#include "project.h"  // This is required for all code generated by PSoC Creator

/* Inclusions for main SeatPM components */
#include "user_interface.h" // for UI class
#include "user_interface_states.h"
#include "buttons.h" // for UI button components
#include "runtime.h" // for runtime class
#include "cpm_runtime.h" // for CPM runtime components
#include "motor.h" // for motor class and components
#include "emergency_stop.h" // for emergency stop function
#include "parameter.h" // for Parameter functions
#ifdef ACCELEROMETER_GONIOMETER_ENABLED
#include "goniometer.h"
#endif

//=============================================================================
// Global Variables
//=============================================================================
UserInterface g_UserInterface;  // UI must be accessed by button press interrupts
Runtime g_CPM_Runtime;   // Interrupt updates seconds
Motor g_CPM_Motor;       // Todo: Make this non-global
#ifdef DISPATCH_IN_MAIN
UserInterface_Signal g_SignalToDispatch;  // Interrupts update this signal for main()
#endif
#ifdef ACCELEROMETER_GONIOMETER_ENABLED
Goniometer g_KneeGoniometer;  // Goniometer can be sampled via interrupt
#endif

//=============================================================================
// Function Prototypes
//=============================================================================
double GetKneeAngle();
void KneeAngleSetup();

//=============================================================================
// Main Function -- Firmware execution starts here!
//=============================================================================
int main(void)
{
    //==========================================================================
    // Startup/Initialization Code
    //==========================================================================
    CyGlobalIntEnable; /* Enable global interrupts. */

    //-------------------------------------------------------------------------
    // Component/"Hardware" Setup

    UI_Buttons_EnableInterrupts();
    KneeAngleSetup();
    PuTTY_Start();

    //-------------------------------------------------------------------------
    // Global Variable Initialization
    UserInterface_Constructor(&g_UserInterface);
    Runtime_Constructor(&g_CPM_Runtime);
    Motor_Constructor(&g_CPM_Motor);
    #ifdef DISPATCH_IN_MAIN
    g_SignalToDispatch = INVALID_SIGNAL;
    #endif
    #ifdef ACCELEROMETER_GONIOMETER
    Goniometer_Constructor(&g_KneeGoniometer);
    #endif

    //-------------------------------------------------------------------------
    // Non-Global Variables
    double LastKneeAngle = INVALID_ANGLE;
    double LastTotalSeconds = 0;

    //=========================================================================
    // Infinite Loop
    //=========================================================================
    for (;;)
    {
        /* Sample the Goniometer*/
        double KneeAngle = g_UserInterface.KneeAngle_Raw = GetKneeAngle();

        bool IsKneeAngleValid =
            Parameter_SetValue(&g_UserInterface.KneeAngle, KneeAngle);

        /* For user safety, always check emeregency stop immediately after
           sampling the goniometer. */
        Handle_EmergencyStop(IsKneeAngleValid, KneeAngle);

        #ifdef DISPATCH_IN_MAIN
        UI_Button_Dispatch(g_SignalToDispatch);
        g_SignalToDispatch = INVALID_SIGNAL;  // Reset signal
        #endif

        /* Update User Interface Display */
        if (UserInterface_ShallUpdateAngleReadingMessage(&g_UserInterface, KneeAngle, LastKneeAngle))
        {
            UserInterface_UpdateAngleReadingMessage(&g_UserInterface, KneeAngle);
            LastKneeAngle = KneeAngle;
        }
        else if (UserInterface_ShallUpdateCPMRuntimeMessage(&g_UserInterface, 
                                               KneeAngle, 
                                               LastKneeAngle,
                                               LastTotalSeconds))
        {
            UserInterface_UpdateCPMRuntimeMessage(&g_UserInterface, KneeAngle);
        }
        #ifdef AUSTIN_DEBUG
        CyDelay(10);  // Necessary for debug output over serial to print
        #endif
    }                 // End infinite loop
}  // End main()

//=============================================================================
// Get Knee Angle (manages potentiometer vs accelerometer goniometer sampling)
//=============================================================================
double GetKneeAngle()
{
#ifdef POTENTIOMETER_GONIOMETER_ENABLED
    // Sample Potentiometer
    Potentiometer_ADC_StartConvert();
    Potentiometer_ADC_IsEndConversion(Potentiometer_ADC_WAIT_FOR_RESULT);
    double Input = (double)Potentiometer_ADC_GetResult16(0);

    // Define Normalization Constants
    const double MaxInput = 2047;  // 11 bits + signed bit
    const double MinInput = 0;
    const double MaxOutput = 180;  // max angle
    const double MinOutput = 90;   // min angle

    // Normalizing function (note: range means max-min)
    return (((Input - MinInput)          // Scale from Zero to Input Range
             / (MaxInput - MinInput)     // Scale from Zero to One
             * (MaxOutput - MinOutput))  // Scale from Zero to Output Range
            + MinOutput);  // Scale from Min to Max Output (normalized)

#else  // Accelerometer Goniometer Enabled
    Goniometer_Sample(&g_KneeGoniometer);
    return (g_KneeGoniometer.CurrentAngle);
#endif
}

//=============================================================================
// Knee Angle Setup (manages potentiometer vs accelerometer goniometer setup)
//=============================================================================
void KneeAngleSetup()
{
#ifdef POTENTIOMETER_GONIOMETER_ENABLED
    // Potentiometer startup
    Potentiometer_ADC_Start();
    Potentiometer_ADC_StartConvert();
#else  // Accelerometer Goniometer Enabled
    Goniometer_Constructor(&g_KneeGoniometer);
#endif
}

//=============================================================================
// Handle Emergency Stop Condition
//=============================================================================
void Handle_EmergencyStop(bool IsKneeAngleValid, double KneeAngle)
{
    if (IsKneeAngleValid == FALSE &&
        g_UserInterface.HasUserSeenAttachAnkleStrapMessage == TRUE)
    {
        // Print to debug what went wrong
        char8 debug[64];
        sprintf(debug,
                "current = %lf,\r\n"
                "val = %lf,\r\n"
                "min = %lf,\r\n"
                "max = %lf\r\n\r\n",
                KneeAngle, 
                Parameter_GetValue(&g_UserInterface.KneeAngle),
                Parameter_GetMinimumValue(&g_UserInterface.KneeAngle),
                Parameter_GetMaximumValue(&g_UserInterface.KneeAngle));
        DEBUG_PRINT(debug);

        EmergencyStop();  // This function stops
                          // everything!!!!!!!!!!!!!!!!!!
    }
}
/* [] END OF FILE */
